export const CHANGE_SET = 'CHANGE_SET';
export const REQUEST_LOADING = 'REQUEST_LOADING';
export const REQUEST_FAIL = 'REQUEST_FAIL';
export const FETCH_CARDS_SUCCESS = 'FETCH_CARDS_SUCCESS';
export const FETCH_CARD_SETS_SUCCESS = 'FETCH_CARD_SETS_SUCCESS';
export const FETCH_EXAMPLE_CARDS_SUCCESS = 'FETCH_EXAMPLE_CARDS_SUCCESS';
export const OPEN_CARD_MODAL = 'OPEN_CARD-MODAL';
export const CLOSE_CARD_MODAL = 'CLOSE_CARD_MODAL';
